// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   apiKey: "AIzaSyBGS1_nlnREDg8VPZb9_FKbkjDu6wraMTQ",
  authDomain: "rmsgold-f76be.firebaseapp.com",
  projectId: "rmsgold-f76be",
  storageBucket: "rmsgold-f76be.firebasestorage.app",
  messagingSenderId: "656232807534",
  appId: "1:656232807534:web:f7ddc2c0c12533ed78ba7f",
  measurementId: "G-GTTMERXPY9",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBGS1_nlnREDg8VPZb9_FKbkjDu6wraMTQ",
  authDomain: "rmsgold-f76be.firebaseapp.com",
  projectId: "rmsgold-f76be",
  storageBucket: "rmsgold-f76be.firebasestorage.app",
  messagingSenderId: "656232807534",
  appId: "1:656232807534:web:f7ddc2c0c12533ed78ba7f",
  measurementId: "G-GTTMERXPY9",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBGS1_nlnREDg8VPZb9_FKbkjDu6wraMTQ",
  authDomain: "rmsgold-f76be.firebaseapp.com",
  projectId: "rmsgold-f76be",
  storageBucket: "rmsgold-f76be.firebasestorage.app",
  messagingSenderId: "656232807534",
  appId: "1:656232807534:web:f7ddc2c0c12533ed78ba7f",
  measurementId: "G-GTTMERXPY9",
    iosBundleId: 'com.rms.rmsgold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBGS1_nlnREDg8VPZb9_FKbkjDu6wraMTQ",
  authDomain: "rmsgold-f76be.firebaseapp.com",
  projectId: "rmsgold-f76be",
  storageBucket: "rmsgold-f76be.firebasestorage.app",
  messagingSenderId: "656232807534",
  appId: "1:656232807534:web:f7ddc2c0c12533ed78ba7f",
  measurementId: "G-GTTMERXPY9",
    iosBundleId: 'com.rms.rmsgold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBGS1_nlnREDg8VPZb9_FKbkjDu6wraMTQ",
  authDomain: "rmsgold-f76be.firebaseapp.com",
  projectId: "rmsgold-f76be",
  storageBucket: "rmsgold-f76be.firebasestorage.app",
  messagingSenderId: "656232807534",
  appId: "1:656232807534:web:f7ddc2c0c12533ed78ba7f",
  measurementId: "G-GTTMERXPY9",
  );
}
